FROM python:3.10-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install rasa-sdk==3.6.2 && \
    pip install -r requirements.txt

COPY actions/ ./actions/

EXPOSE 5055

CMD ["rasa", "run", "actions", "--port", "5055"]